{{ if .Values.ingress.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "elasticsearch.fullname" . }}-kibana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  host: {{ .Values.ingress.hostName }}-kibana.{{ .Values.ingress.baseDomain }}
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect 
    termination: passthrough
  to:
    kind: Service
    name: {{ include "elasticsearch.fullname" . }}-kb-http
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "elasticsearch.fullname" . }}-elastic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  host: {{ .Values.ingress.hostName }}-elastic.{{ .Values.ingress.baseDomain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "elasticsearch.fullname" . }}-es-http
    weight: 100
  wildcardPolicy: None
{{ end }}

  