apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/1/clientConfig/caBundle
      - /webhooks/2/clientConfig/caBundle
      - /webhooks/3/clientConfig/caBundle
      - /webhooks/4/clientConfig/caBundle
      - /webhooks/5/clientConfig/caBundle
      - /webhooks/6/clientConfig/caBundle
      - /webhooks/7/clientConfig/caBundle
      - /webhooks/8/clientConfig/caBundle
      - /webhooks/9/clientConfig/caBundle
  project: default
  destination: 
    namespace: elastic-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/elastic/cloud-on-k8s
    path: deploy/eck-operator
    targetRevision: HEAD
    helm:
      releaseName: eck-operator
      values: |-
        image:
          tag: 1.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true